/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forestsimulator.SQLite;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import treegross.base.GenerateXY;
import treegross.base.Stand;

/**
 *
 * @author nagel
 */
public class JPanelPlots extends javax.swing.JPanel {
     Stand st = null;
     String dir = null;

     String bestaende[] = new String[1000];
     String bestand = "";
     int nBestaende =0;
     int standID =-9;


    /**
     * Creates new form JPanelDatabase
     */
    public JPanelPlots(Stand stx, String dirx) {
        initComponents();
        st = stx;
        dir = dirx+System.getProperty("file.separator")+"fsplots.db";
        String localPath="";
        java.io.File f1 = new java.io.File("");                    
        try{ 
           localPath= f1.getCanonicalPath();
          } catch (Exception e){ }
 
        java.io.File f = new File(dir);
        if ( f.exists()) {
            jLabel1.setText(dir);
        }
        else {
           JFileChooser fc = new JFileChooser();
           DBFileFilter txtFilter = new DBFileFilter();
           txtFilter.setExtension("db");
           fc.addChoosableFileFilter(txtFilter);
           int auswahl = fc.showOpenDialog(this);
           dir = fc.getSelectedFile().getPath();
        }
        jLabel1.setText(dir);
        setVisible(true);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        jButton1.setText("change database file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(2, 4));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Stand ID");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Standname");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Year");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Size [ha]");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel9);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel10);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel11);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.GridLayout(1, 4));

        jButton3.setText("|< first");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jButton4.setText("< back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField1);

        jButton5.setText("search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);

        jButton2.setBackground(new java.awt.Color(246, 187, 239));
        jButton2.setText("save active \nstand");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton7.setText("delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);

        jButton8.setText("next >");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);

        jButton6.setText("last >|");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        DBFileFilter dbFilter = new DBFileFilter();
        dbFilter.setExtension("db");
        fc.addChoosableFileFilter(dbFilter);
        fc.setFileFilter(dbFilter); 
        fc.setAcceptAllFileFilterUsed(true);
        fc.setCurrentDirectory(new File(dir));
                       
        int auswahl = fc.showOpenDialog(this);
        try {
           dir = fc.getSelectedFile().getPath();
           jLabel1.setText(dir);
           setVisible(true);
//           nBestaende=loadBestaende();
        }
        catch (Exception eio){System.out.println(eio);}  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // save stand to database
        if (st.center.no.equalsIgnoreCase("circle")){ 
       
           try{
              Class.forName( "org.sqlite.JDBC" );
              Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
              Statement  stm = cn.createStatement();
              String sqltxt = "INSERT INTO stand (name,size_ha,month,year,lat,lon,masl,region,district,sitetype,exposition_gon,"
                + "slope_percentage) VALUES "+
                "( '"+st.standname+"', "+st.size+", "+st.monat+", "+st.year+", "+st.hochwert_m+", "+st.rechtswert_m+
                ", "+st.hoehe_uNN_m+", '"+st.wuchsgebiet+"', '"+st.wuchsgebiet+"', '"+st.standort+"'"+
                ", "+st.exposition_Gon+", "+st.hangneigungProzent+" )";
               stm.execute(sqltxt);
//  Bestandes ID merken
               sqltxt="SELECT _id FROM stand ORDER BY _id DESC LIMIT 1;";
               standID = -9;
               ResultSet rs = stm.executeQuery(sqltxt);
               while (rs.next()){
                  standID = rs.getInt("_id");
               }             
//           System.out.println("Letzte Id: = "+standID);
//  alle Bäume speichern 
        for (int i=0;i<st.ntrees;i++){
            int w = 0;
            double e = 0.0;
            double dx = st.tr[i].x-st.center.x;
            double dy = st.tr[i].y-st.center.y;
            double ent = Math.sqrt(Math.pow(dx, 2.0)+Math.pow(dy, 2.0));
            double gon = 200.0*Math.asin((dx)/ent)/Math.PI;
            if (dx >=0.0 && dy >=0.0) w=(int) Math.round(gon);
            if (dx >=0.0 && dy <0.0) w=(int) Math.round(200.0-gon);
            if (dx <0.0 && dy <0.0) w=(int) Math.round(Math.abs(gon)+200);
            if (dx <0.0 && dy >=0.0) w=(int) Math.round(400.0-Math.abs(gon));
    
            
            sqltxt = "INSERT INTO trees (standid,code,name,year,age,dbh,h,si,cb,cw,alive,status,azimuth,distance,z,crop,habitat,fac,remarks, layer) VALUES "+
                "( "+standID+", "+st.tr[i].code+", '"+st.tr[i].no+"', "+st.year+", "+st.tr[i].age+", "+st.tr[i].d+", "+st.tr[i].h+", "+st.tr[i].si+
                     ", "+st.tr[i].cb+", "+st.tr[i].cw+", "+st.tr[i].out+", "+st.tr[i].outtype+
                     ", "+w+", "+ent+", "+st.tr[i].z+", '"+st.tr[i].crop+"', '"+st.tr[i].habitat+"', "+st.tr[i].fac+", '"+
                    st.tr[i].remarks+"', "+st.tr[i].layer+"  )";
            stm.execute(sqltxt);
            }
//
        cn.close();     
         } catch (Exception eio){System.out.println(eio);}  
        lastDataset();
       
       }
       else{
            JTextArea about = new JTextArea("not saved: No circular plots");
            JOptionPane.showMessageDialog(this, about, "Error", JOptionPane.INFORMATION_MESSAGE);
       }
   
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // find First
        firstDataset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Find last record
       lastDataset();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
        Class.forName( "org.sqlite.JDBC" );
        Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
        Statement  stm = cn.createStatement();
        String sqltxt="SELECT _id FROM stand WHERE _id < "+standID+" ORDER BY _id DESC LIMIT 1;";
        int idold = standID;
        standID = -9;
        ResultSet rs = stm.executeQuery(sqltxt);
        while (rs.next()){
             standID = rs.getInt("_id");
            }  
        if (standID == -9) standID = idold;
        jLabel8.setText(new Integer(standID).toString());
        cn.close();     
         } catch (Exception eio){System.out.println(eio);} 
        dispStandID();
        // Find next
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Next standid
        nextDataset();
        dispStandID();
        // Find next
 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // delete standID
                try{
        Class.forName( "org.sqlite.JDBC" );
        Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
        Statement  stm = cn.createStatement();
        String sqltxt="DELETE FROM stand WHERE _id = "+standID+" ;";
        ResultSet rs = stm.executeQuery(sqltxt);

        sqltxt="DELETE FROM trees WHERE standid = "+standID+" ;";
        rs = stm.executeQuery(sqltxt);
        cn.close();     
         } catch (Exception eio){System.out.println(eio);} 
        int wert = nextDataset(); 
        if (wert < 0) firstDataset();
        dispStandID();
        // Find next
 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //search stand first by id then by name
        String suche =jTextField1.getText();
        boolean found = false;
        try{
        Class.forName( "org.sqlite.JDBC" );
        Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
        Statement  stm = cn.createStatement();
        String sqltxt="SELECT * FROM stand WHERE _id = "+suche+" ;";
        ResultSet rs = stm.executeQuery(sqltxt);
        while (rs.next()){
            standID = rs.getInt("_id");
            found = true;
        } 
        cn.close(); 
         } catch (Exception eio){System.out.println(eio);}  
        try{
        if (found != true){
           Class.forName( "org.sqlite.JDBC" );
           Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
           Statement  stm = cn.createStatement();
            String sqltxt="SELECT * FROM stand WHERE name like '"+suche+"' ;";
            ResultSet rs = stm.executeQuery(sqltxt);
            while (rs.next()){
                standID = rs.getInt("_id");
               found = true;
            } 
                
        cn.close(); 
        }
         } catch (Exception eio){System.out.println(eio);}  
        if (found) dispStandID(); 
        

       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void dispStandID(){
        try{
        Class.forName( "org.sqlite.JDBC" );
        Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
        Statement  stm = cn.createStatement();
        String sqltxt="SELECT * FROM stand WHERE _id = "+standID+" ;";
        ResultSet rs = stm.executeQuery(sqltxt);
        while (rs.next()){
            jLabel8.setText(new Integer(standID).toString());
            jLabel9.setText(rs.getString("name"));
            jLabel10.setText(new Integer(rs.getInt("year")).toString());
            jLabel11.setText(rs.getString("size_ha"));
            }  
        
        cn.close();     
         } catch (Exception eio){System.out.println(eio);}  
        // Find next
        
    }
    
    private int nextDataset(){
      int erg=-9;  
      try{
        Class.forName( "org.sqlite.JDBC" );
        Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
        Statement  stm = cn.createStatement();
        String sqltxt="SELECT _id FROM stand WHERE _id > "+standID+" ORDER BY _id LIMIT 1;";
        int idold = standID;
        standID = -9;
        ResultSet rs = stm.executeQuery(sqltxt);
        while (rs.next()){
             standID = rs.getInt("_id");
             erg = standID;
            }  
        if (standID == -9) standID = idold;
        jLabel8.setText(new Integer(standID).toString());
        cn.close();     
         } catch (Exception eio){System.out.println(eio);}  
        dispStandID();
        return erg;
    }
    
        private int firstDataset(){
      int erg=-9;  
       try{
        Class.forName( "org.sqlite.JDBC" );
        Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
        Statement  stm = cn.createStatement();
        String sqltxt="SELECT _id FROM stand ORDER BY _id LIMIT 1;";
        standID = -9;
        ResultSet rs = stm.executeQuery(sqltxt);
        while (rs.next()){
             standID = rs.getInt("_id");
            }             
        jLabel8.setText(new Integer(standID).toString());
        cn.close();     
       } catch (Exception eio){System.out.println(eio);} 
        dispStandID();
        return erg;
    }
        
        private int lastDataset(){
            int erg = -9;
            try{
               Class.forName( "org.sqlite.JDBC" );
               Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
               Statement  stm = cn.createStatement();
               String sqltxt="SELECT _id FROM stand ORDER BY _id DESC LIMIT 1;";
               standID = -9;
               ResultSet rs = stm.executeQuery(sqltxt);
               while (rs.next()){
                  standID = rs.getInt("_id");
                  erg=standID;
               }             
               jLabel8.setText(new Integer(standID).toString());
               cn.close();     
            } catch (Exception eio){System.out.println(eio);}  
            dispStandID();
            return erg;
        }
        
    public Stand createStand(){
        try{
        Class.forName( "org.sqlite.JDBC" );
        Connection cn = DriverManager.getConnection("jdbc:sqlite:"+dir, "", "" );
        Statement  stm = cn.createStatement();
        String sqltxt="SELECT * FROM stand WHERE _id = "+standID+" ;";
        ResultSet rs = stm.executeQuery(sqltxt);
        while (rs.next()){
             st.standname = rs.getString("name");
             st.year = rs.getInt("year");
             st.size = Double.parseDouble(rs.getString("size_ha"));
             st.monat = rs.getInt("month");
             st.rechtswert_m = Double.parseDouble(rs.getString("lat"));
             st.hochwert_m = Double.parseDouble(rs.getString("lon"));
             st.hoehe_uNN_m = Double.parseDouble(rs.getString("masl"));
             st.wuchsgebiet = rs.getString("region");
             st.wuchsbezirk = rs.getString("district");
             st.standort = rs.getString("sitetype");
             st.exposition_Gon = (int)(Math.round(Double.parseDouble(rs.getString("exposition_gon"))));
             st.hangneigungProzent = Double.parseDouble(rs.getString("slope_percentage"));
        }  
        double radius = Math.sqrt(st.size*10000/Math.PI);
        st.ncpnt=0;
        st.center.no="circle";
        st.center.x = radius;
        st.center.y = radius;
        st.center.z = 0.0;
        for (int i=0; i<20;i++){
            double w = 20.0*i;
            double xx=radius+Math.sin(Math.PI*w/200.0)*radius;
            double yy=radius+Math.cos(Math.PI*w/200.0)*radius;
            double zz = 0.0;
            st.addcornerpoint("Eck"+i, xx, yy, zz);
        }  
        sqltxt="SELECT * FROM trees WHERE standid = "+standID+" ;";
        rs = stm.executeQuery(sqltxt);
        st.ntrees=0;
        while (rs.next()){
             String na = rs.getString("name");
             int cc = rs.getInt("code");
             int aa = rs.getInt("age");
             double dd = Double.parseDouble(rs.getString("dbh"));
             double hh = Double.parseDouble(rs.getString("h"));
             double si = Double.parseDouble(rs.getString("si"));
             double ccb = Double.parseDouble(rs.getString("cb"));
             double ccw = Double.parseDouble(rs.getString("cw"));
             int oout = rs.getInt("alive");
             int oouttype = rs.getInt("status");
             boolean ccrop = Boolean.parseBoolean(rs.getString("crop"));
             boolean hhabitat = Boolean.parseBoolean(rs.getString("habitat"));
             boolean tz = false;
             String rm = rs.getString("remarks");        
             double e = Double.parseDouble(rs.getString("distance"));
             double w = Double.parseDouble(rs.getString("azimuth"));
             double zz = Double.parseDouble(rs.getString("z"));
             double ff = Double.parseDouble(rs.getString("fac"));
             int lay = rs.getInt("layer");
             double xx=radius+Math.sin(Math.PI*w/200.0)*e;
             double yy=radius+Math.cos(Math.PI*w/200.0)*e;
             int nclone=1;
             if (ff >= 2.0){
                nclone = (int) Math.floor(ff); 
                ff = ff/Math.floor(ff); 
             }
             for (int k=0; k<nclone;k++){
                 String nam = na;
                 if (k > 0) { 
                     nam=na+"_"+k;
                     xx = -9.0;
                     yy = -9.0;
                 }
                 st.addXMLTree(cc, nam, aa, oout, oouttype, dd, hh, ccb, ccw, si, ff, xx, yy, zz, ccrop, tz, hhabitat, 0, 0.0, rm);
                 st.tr[st.ntrees-1].layer = lay;
                 
             }
        }
        cn.close();     
         } catch (Exception eio){System.out.println(eio);}  

        st.missingData();
        GenerateXY gen = new GenerateXY();
        gen.zufall(st);
        st.descspecies(); 
       return(st);

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
