package forestsimulator.dbaccess;

import java.awt.Frame;
import java.text.MessageFormat;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JProgressBar;
import javax.swing.WindowConstants;

public class BatchProgressDialog extends JDialog implements BatchProgressListener {

    private static final ResourceBundle messages = java.util.ResourceBundle.getBundle("forestsimulator/gui"); // NOI18N
        
    private final BatchProcessingControl batchControl;

    public BatchProgressDialog(Frame parent, String databaseFile, BatchProcessingControl batchControl) {
        super(parent);
        initComponents();
        this.batchControl = batchControl;
        infoLabel.setText(MessageFormat.format(messages.getString("BatchProcessingProgressPanel.infoLabel.text"), databaseFile));
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        currentRuleLabel = new javax.swing.JLabel();
        currentRuleDisplay = new javax.swing.JLabel();
        ruleProgressLabel = new javax.swing.JLabel();
        ruleProgress = new javax.swing.JProgressBar();
        passProgress = new javax.swing.JProgressBar();
        passProgressLabel = new javax.swing.JLabel();
        stepProgressLabel = new javax.swing.JLabel();
        stepProgress = new javax.swing.JProgressBar();
        stopButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("forestsimulator/gui"); // NOI18N
        setTitle(bundle.getString("BatchProgressDialog.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        infoLabel.setText(bundle.getString("BatchProcessingProgressPanel.infoLabel.text")); // NOI18N

        currentRuleLabel.setText(bundle.getString("BatchProgressDialog.currentRuleLabel.text")); // NOI18N

        ruleProgressLabel.setText(bundle.getString("BatchProcessingProgressPanel.ruleProgressLabel.text")); // NOI18N

        ruleProgress.setString(""); // NOI18N
        ruleProgress.setStringPainted(true);

        passProgress.setString(""); // NOI18N
        passProgress.setStringPainted(true);

        passProgressLabel.setText(bundle.getString("BatchProcessingProgressPanel.passProgressLabel.text")); // NOI18N

        stepProgressLabel.setText(bundle.getString("BatchProgressDialog.stepProgressLabel.text")); // NOI18N

        stepProgress.setString(""); // NOI18N
        stepProgress.setStringPainted(true);

        stopButton.setText(bundle.getString("BatchProcessingProgressPanel.stopButton.text")); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
        progressPanel.setLayout(progressPanelLayout);
        progressPanelLayout.setHorizontalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(progressPanelLayout.createSequentialGroup()
                        .addComponent(infoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(progressPanelLayout.createSequentialGroup()
                        .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentRuleLabel)
                            .addComponent(ruleProgressLabel)
                            .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(passProgressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stepProgressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stepProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(passProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ruleProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentRuleDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(stopButton)))
                .addContainerGap())
        );
        progressPanelLayout.setVerticalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(currentRuleLabel)
                    .addComponent(currentRuleDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ruleProgressLabel)
                    .addComponent(ruleProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passProgressLabel)
                    .addComponent(passProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stepProgressLabel)
                    .addComponent(stepProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(stopButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        initiateStop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        initiateStop();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentRuleDisplay;
    private javax.swing.JLabel currentRuleLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JProgressBar passProgress;
    private javax.swing.JLabel passProgressLabel;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JProgressBar ruleProgress;
    private javax.swing.JLabel ruleProgressLabel;
    private javax.swing.JProgressBar stepProgress;
    private javax.swing.JLabel stepProgressLabel;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateProgress(BatchProgress progress) {
        currentRuleDisplay.setText(progress.currentRuleText());
        updateProgressBar(ruleProgress, progress.ruleProgress());
        updateProgressBar(passProgress, progress.passProgress());
        updateProgressBar(stepProgress, progress.stepProgress());
    }

    private void updateProgressBar(JProgressBar bar, Progress progress) {
        bar.setMaximum(progress.total);
        bar.setValue(progress.current);
        bar.setString(progressString(progress));
    }

    public String progressString(Progress progress) {
        return progress.current + " / " + progress.total;
    }

    private void initiateStop() {
        batchControl.stopProcessing();
        stopButton.setText(messages.getString("BatchProgressDialog.stopButton.stopping.text")); // NOI18N
    }
    
    @Override
    public void aborted() {
        dispose();
    }
}
