/*
* @(#) DBAccessDialog.java
*  (c) 2002-2010 Juergen Nagel, Northwest German Research Station,
*      Grätzelstr.2, 37079 Göttingen, Germany
*      E-Mail: Juergen.Nagel@nw-fva.de
*
*  This program is free software; you can redistribute it and/or
*  modify it under the terms of the GNU General Public License
*  as published by the Free Software Foundation.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*/
package forestsimulator.dbaccess;
import forestsimulator.util.StandGeometry;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import treegross.base.*;
import treegross.treatment.*;
import treegross.random.RandomNumber;
import java.sql.*;
import java.text.MessageFormat;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


/** TreeGrOSS : DBAccessDialog.java
 *  version 	7.5 18-Mar-2010
 *  author	Juergen Nagel
 *
 * This dialog class is used only special data management of the NW-FVA and it is not documented.
 * It reads a forest stand from the data base structure of the NW-FVA
 */
public class DBAccessDialog extends JDialog {
    private Stand st;
    int growthCycles = 0;
    private final ConnectionFactory connectionFactory = new ConnectionFactory();
    private final ResourceBundle messages = ResourceBundle.getBundle("forestsimulator/gui");
    
    public DBAccessDialog(Frame parent, boolean modal, Stand stand, File dir) {
        super(parent, modal);
        initComponents();
        st = stand;
        databaseFilenameTextField.setText(new File(dir, "localdata.mdb").getPath());
        elsaltoPanel.setVisible(false);
        calculateStandButton.setVisible(false);
        if (st.FileXMLSettings.indexOf("ElSalto") > 0) {
            elsaltoPanel.setVisible(true);
        }
        pack();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        simulationButton = new javax.swing.JButton();
        biDataLabel = new javax.swing.JLabel();
        feDataButton = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        loadCircleButton = new javax.swing.JButton();
        yearsLabel = new javax.swing.JLabel();
        yearsTextField = new javax.swing.JTextField();
        biUpdateButton = new javax.swing.JButton();
        beginCheckBox = new javax.swing.JCheckBox();
        biPlotInfoButton = new javax.swing.JButton();
        elsaltoPanel = new javax.swing.JPanel();
        loadSPISButton = new javax.swing.JButton();
        plotNumberLabel = new javax.swing.JLabel();
        plotNumberTextField = new javax.swing.JTextField();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        standNameTextField = new javax.swing.JTextField();
        databaseFilenameTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        searchButton = new javax.swing.JButton();
        selectFileButton = new javax.swing.JButton();
        specialMixtureButton = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        loadStandButton = new javax.swing.JButton();
        calculateStandButton = new javax.swing.JButton();
        calculateAllButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        updateViewCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("forestsimulator/gui"); // NOI18N
        setTitle(bundle.getString("DBAccessDialog.title")); // NOI18N

        simulationButton.setText(bundle.getString("DBAccessDialog.simulationButton.text")); // NOI18N
        simulationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulationButtonActionPerformed(evt);
            }
        });

        biDataLabel.setText(bundle.getString("DBAccessDialog.biDataLabel.text")); // NOI18N

        feDataButton.setText(bundle.getString("DBAccessDialog.feDataButton.text")); // NOI18N
        feDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feDataButtonActionPerformed(evt);
            }
        });

        jTextField3.setText("179-2001-001"); // NOI18N

        jTextField4.setText("4172"); // NOI18N

        jTextField6.setText("179-2009-001"); // NOI18N

        loadCircleButton.setText(bundle.getString("DBAccessDialog.loadCircleButton.text")); // NOI18N
        loadCircleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCircleButtonActionPerformed(evt);
            }
        });

        yearsLabel.setText(bundle.getString("DBAccessDialog.yearsLabel.text")); // NOI18N

        yearsTextField.setText("10"); // NOI18N
        yearsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsTextFieldActionPerformed(evt);
            }
        });

        biUpdateButton.setText(bundle.getString("DBAccessDialog.biUpdateButton.text")); // NOI18N
        biUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biUpdateButtonActionPerformed(evt);
            }
        });

        beginCheckBox.setText(bundle.getString("DBAccessDialog.beginCheckBox.text")); // NOI18N

        biPlotInfoButton.setText(bundle.getString("DBAccessDialog.biPlotInfoButton.text")); // NOI18N
        biPlotInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biPlotInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(biUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(beginCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(feDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadCircleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biPlotInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadCircleButton)
                    .addComponent(biDataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(biUpdateButton)
                            .addComponent(beginCheckBox)
                            .addComponent(biPlotInfoButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feDataButton)
                            .addComponent(simulationButton)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yearsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearsLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loadSPISButton.setText(bundle.getString("DBAccessDialog.loadSPISButton.text")); // NOI18N
        loadSPISButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSPISButtonActionPerformed(evt);
            }
        });

        plotNumberLabel.setText(bundle.getString("DBAccessDialog.plotNumberLabel.text")); // NOI18N

        plotNumberTextField.setText("1"); // NOI18N
        plotNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotNumberTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout elsaltoPanelLayout = new javax.swing.GroupLayout(elsaltoPanel);
        elsaltoPanel.setLayout(elsaltoPanelLayout);
        elsaltoPanelLayout.setHorizontalGroup(
            elsaltoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elsaltoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plotNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plotNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadSPISButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        elsaltoPanelLayout.setVerticalGroup(
            elsaltoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elsaltoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(elsaltoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadSPISButton)
                    .addComponent(plotNumberLabel)
                    .addComponent(plotNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        standNameTextField.setText("test0001"); // NOI18N

        databaseFilenameTextField.setText(bundle.getString("DBAccessDialog.databaseFilenameTextField.text")); // NOI18N

        searchButton.setText(bundle.getString("DBAccessDialog.searchButton.text")); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        selectFileButton.setText(bundle.getString("DBAccessDialog.selectFileButton.text")); // NOI18N
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        specialMixtureButton.setText(bundle.getString("DBAccessDialog.specialMixtureButton.text")); // NOI18N
        specialMixtureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialMixtureButtonActionPerformed(evt);
            }
        });

        jButton14.setText(bundle.getString("DBAccessDialog.jButton14.text")); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        loadStandButton.setText(bundle.getString("DBAccessDialog.loadStandButton.text")); // NOI18N
        loadStandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadStandButtonActionPerformed(evt);
            }
        });

        calculateStandButton.setText(bundle.getString("DBAccessDialog.calculateStandButton.text")); // NOI18N
        calculateStandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateStandButtonActionPerformed(evt);
            }
        });

        calculateAllButton.setText(bundle.getString("DBAccessDialog.calculateAllButton.text")); // NOI18N
        calculateAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateAllButtonActionPerformed(evt);
            }
        });

        jButton5.setText(bundle.getString("DBAccessDialog.saveStandToDatabase.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        updateViewCheckbox.setSelected(true);
        updateViewCheckbox.setText(bundle.getString("DBAccessDialog.updateViewCheckbox.text")); // NOI18N
        updateViewCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateViewCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loadStandButton)
                        .addGap(14, 14, 14)
                        .addComponent(calculateStandButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calculateAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateViewCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(standNameTextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(databaseFilenameTextField)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(562, 562, 562)
                                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(specialMixtureButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(specialMixtureButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFileButton)
                    .addComponent(databaseFilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadStandButton)
                    .addComponent(calculateStandButton)
                    .addComponent(calculateAllButton)
                    .addComponent(jButton5)
                    .addComponent(updateViewCheckbox))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(elsaltoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(elsaltoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        final String standName = standNameTextField.getText();
        boolean standFound = false;
        try (Connection connection = connectionFactory.openDBConnection(aktivesDatenfile, "", "");
                PreparedStatement stmt = connection.prepareStatement("SELECT * FROM Auf WHERE edvid = ?")) {
            stmt.setString(1, standName);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    standFound = true;
                    jComboBox1.addItem(rs.getInt("auf"));
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(DBAccessDialog.class.getName()).log(Level.SEVERE, "Problem with database", e);
        }
        if (!standFound) {
            JOptionPane.showMessageDialog(rootPane, MessageFormat.format(messages.getString("DBAccessDialog.stand.not.found.message"), standName));
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void loadStandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStandButtonActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        LoadTreegrossStand lts = new LoadTreegrossStand();

        String ids = standNameTextField.getText();
        Object txt = jComboBox1.getSelectedItem();

        int aufs = Integer.parseInt(txt.toString());

        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            st = lts.loadFromDB(con, st, ids, aufs, true, true);
            st.sortbyd();
            st.missingData();
            GenerateXY gxy = new GenerateXY();
            gxy.zufall(st);
            // Test if all trees are in area           
            for (int k = 0; k < st.ntrees; k++) {
                if (StandGeometry.pnpoly(st.tr[k].x, st.tr[k].y, st) == 0) {
                    st.tr[k].out = 1900;
                    st.tr[k].outtype = 1;
                }
            }
            st.descspecies();
// Define all trees with fac = 0.0 as dead zu that there is no growth          
            for (int k = 0; k < st.ntrees; k++) {
                if (st.tr[k].fac == 0.0) {
                    st.tr[k].out = 1900;
                    st.tr[k].outtype = 1;
                }
            }
            st.descspecies();
        } catch (Exception e) {
            System.out.println("Problem: " + " " + e);
        }

        dispose();
    }//GEN-LAST:event_loadStandButtonActionPerformed

    private void calculateStandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateStandButtonActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        try (Connection con = connectionFactory.openDBConnection(aktivesDatenfile, "", "")) {
            Treatment2 t2 = new Treatment2();
            LoadTreegrossStand lts = new LoadTreegrossStand();
            String ids = standNameTextField.getText();
            Object txt = jComboBox1.getSelectedItem();

            int aufs = Integer.parseInt(txt.toString());

            st = lts.loadFromDB(con, st, ids, aufs, true, true);
            st.sortbyd();
            st.missingData();
            GenerateXY gxy = new GenerateXY();
            gxy.zufall(st);
            st.descspecies();
            st = lts.loadRules(con, st, ids, aufs, t2, 0);
            lts.saveBaum(con, st, ids, aufs, 0, 0);
            for (int i = 0; i < st.temp_Integer; i++) {
                st.grow(5, false);
                st.sortbyd();
                st.missingData();
                st.descspecies();
                lts.saveBaum(con, st, ids, aufs, i + 1, 0);
            }
        } catch (SQLException e) {
            System.out.println("Problem: " + " " + e);
        }
        dispose();
    }//GEN-LAST:event_calculateStandButtonActionPerformed

    private void calculateAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateAllButtonActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        AllCalculationRulesProcessor processor = new AllCalculationRulesProcessor(aktivesDatenfile, st, updateViewCheckbox.isSelected());
        BatchProgressDialog progress = new BatchProgressDialog((Frame) getParent(), new File(aktivesDatenfile).getName(), processor);
        processor.setProgressListener(progress);
        progress.pack();
        progress.setLocationRelativeTo(getOwner());
        progress.setVisible(true);
        processor.execute();
        dispose();
    }//GEN-LAST:event_calculateAllButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            LoadTreegrossStand lts = new LoadTreegrossStand();
            lts.saveXMLToDB(con, st);
        } catch (Exception e) {
            System.out.println("Problem: " + " " + e);
        }
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        // Select data base file
        File f = new File("");
        String localPath = "";
        try {
            localPath = f.getCanonicalPath();
        } catch (IOException e) {
        }
        javax.swing.JFileChooser jf = new javax.swing.JFileChooser();
        jf.setCurrentDirectory(new File(localPath));
        jf.showOpenDialog(this);
        File verzeichnis = jf.getSelectedFile();
        databaseFilenameTextField.setText(verzeichnis.getAbsolutePath());
    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void loadSPISButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSPISButtonActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            LoadProbekreis lpk = new LoadProbekreis();
            int pl = Integer.parseInt(plotNumberTextField.getText());
            st = lpk.loadFromElSalto(con, st, pl);
        } catch (Exception e) {
            System.out.println("Problem: " + " " + e);
        }
        st.missingData();
        GenerateXY gxy = new GenerateXY();
        gxy.setGroupRadius(0.0);
        gxy.zufall(st);
        st.sortbyd();
        st.descspecies();
        st.random.setRandomType(RandomNumber.PSEUDO);
        dispose();
    }//GEN-LAST:event_loadSPISButtonActionPerformed

    private void specialMixtureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialMixtureButtonActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            LoadTreegrossStand lts = new LoadTreegrossStand();
            String ids = "95650200";
            int aufs = 8;
            try (Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery("SELECT * FROM AufRun   ")) {
                while (rs.next()) {
                    ids = rs.getString("edvid");
                    aufs = rs.getInt("auf");

                    st = lts.loadFromDB(con, st, ids, aufs, true, true);
                    st.sortbyd();
                    for (int k = 0; k < st.ntrees; k++) {
                        if (st.tr[k].code == 320) {
                            st.tr[k].code = 321;
                        }
                    }
                    st.missingData();
                    GenerateXY gxy = new GenerateXY();
                    gxy.zufall(st);
                    // Test if all trees are in area           
                    for (int k = 0; k < st.ntrees; k++) {
                        if (StandGeometry.pnpoly(st.tr[k].x, st.tr[k].y, st) == 0) {
                            st.tr[k].out = 1900;
                            st.tr[k].outtype = 1;
                        }
                    }
                    st.descspecies();
// Define all trees with fac = 0.0 as dead zu that there is no growth          
                    for (int k = 0; k < st.ntrees; k++) {
                        if (st.tr[k].fac == 0.0) {
                            st.tr[k].out = 1900;
                            st.tr[k].outtype = 1;
                        }
                    }
                    st.descspecies();
                }
            }
// Daten speichern        
            aktivesDatenfile = databaseFilenameTextField.getText();
            try (Connection connection = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
                MixedTreeInfo mti = new MixedTreeInfo();
                mti.saveTreeInfo(connection, st, ids, aufs);

                lts.saveSpecies(connection, st, ids, aufs, 0, 0);
            }
            System.out.println("edvis auf fertig: " + ids + "  " + aufs);
        } catch (SQLException ex) {
            Logger.getLogger(DBAccessDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_specialMixtureButtonActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        LoadTreegrossStand lts = new LoadTreegrossStand();
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            for (int ib = 0; ib < 16; ib++) {
                int bestand = ib;
                for (int j = 0; j < 9; j++) {
                    double mix = 0.0;
                    for (int i = 0; i < 21; i++) {
                        int art1 = 211;
                        int art2 = 511;
                        Double v211B = 0.0;
                        Double v511B = 0.0;
                        Double v211E = 0.0;
                        Double v511E = 0.0;
                        Double c66B = 0.0;
                        Double c66F = 0.0;
                        st = lts.newStand(st, "FiBu", 0.5);

                        double mix1 = mix + i * 0.05;
                        double mix2 = 1.0 - i * 0.05;
                        if (mix1 > 0) {
                            st = lts.addLayerFromStartwert(con, st, bestand, art1, mix1);
                        }
                        if (mix2 > 0) {
                            st = lts.addLayerFromStartwert(con, st, bestand, art2, mix2);
                        }
                        for (int ii = 0; ii < st.nspecies; ii++) {
                            if (st.sp[ii].code == 211) {
                                v211B = st.getVha(211);
                            }
                            if (st.sp[ii].code == 511) {
                                v511B = st.getVha(511);
                            }
                        }
                        lts.saveSpecies(con, st, "FiBu", i * 5, bestand, st.year);
                        st.grow(5, false);
                        st.descspecies();
                        lts.saveSpecies(con, st, "FiBu", i, bestand, st.year);
                        for (int ii = 0; ii < st.nspecies; ii++) {
                            if (st.sp[ii].code == 211) {
                                v211E = st.getVha(211);
                                int anz = 0;
                                for (int jj = 0; jj < st.ntrees; jj++) {
                                    if (st.tr[jj].code == 211 && st.tr[jj].out < 0) {
                                        c66B = c66B + st.tr[jj].c66xy;
                                        anz = anz + 1;
                                    }
                                }
                                if (anz > 0) {
                                    c66B = c66B / anz;
                                }
                            }
                            if (st.sp[ii].code == 511) {
                                v511E = st.getVha(511);
                                int anz = 0;
                                for (int jj = 0; jj < st.ntrees; jj++) {
                                    if (st.tr[jj].code == 511 && st.tr[jj].out < 0) {
                                        c66F = c66F + st.tr[jj].c66xy;
                                        anz = anz + 1;
                                    }
                                }
                                if (anz > 0) {
                                    c66F = c66F / anz;
                                }

                            }
                        }
                        try (PreparedStatement stmt = con.prepareStatement("INSERT INTO Produktivitaet ( Bestand, MixBu, V1Art1, V1Art2, V2Art1, V2Art2, c66xyArt1, c66xyArt2) values (?, ?, ?, ?, ?, ?, ?, ?)")) {
                            int bum = i * 5;
                            stmt.setInt(1, bestand);
                            stmt.setInt(2, bum);
                            stmt.setDouble(3, v211B);
                            stmt.setDouble(4, v511B);
                            stmt.setDouble(5, v211E);
                            stmt.setDouble(6, v511E);
                            stmt.setDouble(7, c66B);
                            stmt.setDouble(8, c66F);
                            stmt.execute();
                        } catch (SQLException e) {
                            System.out.println("Datenbank Stammv :" + e);
                        }
                        System.out.println("Fertig " + ib + "  " + j);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DBAccessDialog.class.getName()).log(Level.SEVERE, "Problem with database", ex);
        }
        dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void plotNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plotNumberTextFieldActionPerformed

    private void biPlotInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biPlotInfoButtonActionPerformed
        // BI Plot Info
        boolean beginnPeriode = beginCheckBox.isSelected();
        LoadTreegrossStand lts = new LoadTreegrossStand();
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();     // a class to manage the conection to a database

        String bi = "179-2001-001";
        String bi2 = " ";
        //        String bi2 = "";
        String pk = "4172";

        String orga[] = new String[300];
        int norga = 0;

        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            try (Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery("SELECT * FROM tblDatOrga")) {
                while (rs.next()) {
                    int stj = rs.getInt("DatOrga_Stj");
                    if (stj >= 1990) {
                        orga[norga] = rs.getString("DatOrga_Key");
                        norga = norga + 1;
                    }
                }
            }
            for (int inventur = 0; inventur < norga; inventur++) {

                bi = orga[inventur];
                bi2 = "";
                int type = 2;
                /*        if (beginnPeriode == false){
                if (bi.indexOf("167") >= 0) bi2="167-2009-001";
                if (bi.indexOf("172") >= 0) bi2="172-2008-001";
                if (bi.indexOf("179") >= 0) bi2="179-2009-001";
                if (bi.indexOf("262") >= 0) bi2="262-2009-001";
                if (bi.indexOf("268") >= 0) bi2="268-2011-001";
                if (bi.indexOf("269") >= 0) bi2="269-2008-001";
                if (bi.indexOf("273") >= 0) bi2="273-2008-001";
                type=3;
            }
                 */

                int kr[] = new int[10000];
                int nkr = 0;
                try (PreparedStatement stmt = con.prepareStatement("SELECT * FROM tblDatPh2 WHERE DatOrga_Key = ?")) {
                    stmt.setString(1, bi);
                    try (ResultSet rs = stmt.executeQuery()) {
                        while (rs.next()) {
                            kr[nkr] = rs.getInt("DatPh2_KSPNr");
                            nkr = nkr + 1;
                        }
                    }
                } catch (Exception e) {
                    System.out.println("Problem: " + " " + e);
                }

                for (int kreis = 0; kreis < nkr; kreis++) {

                    LoadProbekreis lpk = new LoadProbekreis();

                    st = lpk.loadFromDB(con, st, bi, kr[kreis], bi2, type);
                    st.missingData();
                    for (int i = 0; i < st.ntrees; i++) {
                        if (st.tr[i].out > 0) {
                            st.tr[i].outtype = 2;
                        }
                    }
                    GenerateXY gxy = new GenerateXY();
                    gxy.setGroupRadius(0.0);
                    gxy.zufall(st);
                    st.sortbyd();
                    st.descspecies();
                    lts.saveStandV2(con, st, bi, kr[kreis], type, st.year, st.bt);
                    lts.saveSpecies(con, st, bi, kr[kreis], type, st.year);

                    System.out.println(kreis + "  FERTIG PLOT: " + bi + " " + kr[kreis]);

                } // Kreise
            } // Inventur
        } catch (SQLException e) {
            Logger.getLogger(DBAccessDialog.class.getName()).log(Level.SEVERE, "Problem with database.", e);
        }
        dispose();
    }//GEN-LAST:event_biPlotInfoButtonActionPerformed

    private void biUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biUpdateButtonActionPerformed
        LoadTreegrossStand lts = new LoadTreegrossStand();
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            String bi = "179-2001-001";
            String pk = "4172";

            String orga[] = new String[900];
            int norga = 0;

            try (Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT * FROM tblDatOrga  ")) {
                while (rs.next()) {
                    int stj = rs.getInt("DatOrga_Stj");
                    /**
                     * Änderung 2008 nach 2018
                     */
                    if (stj < 2018) {
                        orga[norga] = rs.getString("DatOrga_Key");
                        norga = norga + 1;
                    }
                }
            } catch (SQLException e) {
                System.out.println("Problem: " + " " + e);
            }

            for (int inventur = 0; inventur < norga; inventur++) {

                bi = orga[inventur];
                int kr[] = new int[90000];
                int nkr = 0;
                try (PreparedStatement stmt = con.prepareStatement("SELECT * FROM tblDatPh2 WHERE DatOrga_Key = ?")) {
                    stmt.setString(1, bi);
                    try (ResultSet rs = stmt.executeQuery()) {
                        while (rs.next()) {
                            kr[nkr] = rs.getInt("DatPh2_KSPNr");
                            nkr = nkr + 1;
                        }
                    }
                } catch (Exception e) {
                    System.out.println("Problem: " + " " + e);
                }

                for (int kreis = 0; kreis < nkr; kreis++) {

                    LoadProbekreis lpk = new LoadProbekreis();

                    st = lpk.loadFromDB(con, st, bi, kr[kreis], "", 1);
                    st.missingData();
                    GenerateXY gxy = new GenerateXY();
                    gxy.setGroupRadius(0.0);
                    gxy.zufall(st);
                    st.sortbyd();
                    st.descspecies();

                    /*        st.randomGrowthEffects=false;
                    st.ingrowthActive = false;
                    st.riskActive = true;
                    st.distanceDependent=true;
                    Treatment2 treatment2 = new Treatment2();

                    if (st.bt > 0 )
                    treatment2.setBT(st);

                    treatment2.setAutoPlanting(st, false, false, 0.2, "511");
                    treatment2.setSkidTrails(st, false, 20.0, 4.0);
                    treatment2.setNatureProtection(st, 0,0,false,0.1,200);
                    treatment2.setHarvestRegime(st, 0, 0, 80, 0.1, "0.3;");
                    treatment2.setThinningRegime(st, 0,1.0,10,60,false);
                     */
                    //        lts.saveStandV2(dbconnAC, st, bi , kr[kreis], 1, st.year, st.bt);
                    //        lts.saveSpecies(dbconnAC, st, bi , kr[kreis], 1, st.year);
                    /*
                    for (int ngr =0; ngr <2; ngr++){
                        treatment2.executeManager2(st);
                        st.descspecies();
                        st.executeMortality();
                        st.descspecies();
                        st.grow(5, false);
                        st.descspecies();
                    }
                     */
                    lts.saveStandV2(con, st, bi, kr[kreis], 1, st.year, st.bt);
                    //        lts.saveBaum(con, st, bi , kr[kreis], 1, st.year);
                    lts.saveSpeciesV2(con, st, bi, kr[kreis], 1, st.year);
                    System.out.println(inventur + " " + bi + " " + kreis + "  FERTIG PLOT: " + kr[kreis]);

                } // Kreise

            } // inventur
        } catch (Exception e) {
            System.out.println("Problem: " + " " + e);
        }
        dispose();
    }//GEN-LAST:event_biUpdateButtonActionPerformed

    private void yearsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsTextFieldActionPerformed

    private void loadCircleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCircleButtonActionPerformed
        // BI Probekreis laden
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            LoadProbekreis lpk = new LoadProbekreis();
            int pl = Integer.parseInt(jTextField4.getText());
            st = lpk.loadFromDB(con, st, jTextField3.getText(), pl, jTextField6.getText(),1);
        } catch (Exception e){  System.out.println("Problem: "+" "+e); }
        st.missingData();
        GenerateXY gxy = new GenerateXY();
        gxy.setGroupRadius(0.0);
        gxy.zufall(st);
        st.sortbyd();
        st.descspecies();

        st.random.setRandomType(RandomNumber.PSEUDO);

        Treatment2 treatment2 = new Treatment2();
        treatment2.setAutoPlanting(st, false, false, 0.2, "511");
        treatment2.setSkidTrails(st, false, 20.0, 4.0);
        treatment2.setNatureProtection(st, 0,0,false,0.1,200);
        treatment2.setHarvestRegime(st, 0, 0, 80, 0.1, "0.3;");
        treatment2.setThinningRegime(st, 2,1.0,10,60,false);

        dispose();
    }//GEN-LAST:event_loadCircleButtonActionPerformed

    private void feDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feDataButtonActionPerformed
        // TFE Daten
        String aktivesDatenfile = databaseFilenameTextField.getText();
        ConnectionFactory dbconnAC = new ConnectionFactory();
        double hg = 0.0;
        double dg = 0.0;
        double dmax = 0.0;
        double g = 0.0;
        double h100 = 0.0;
        String id = "test";
        int art = 0;
        int alt = 0;
        Integer nummer = 0;
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            try (Statement stmt = con.createStatement(); ResultSet rsx = stmt.executeQuery("select * from BucheRein2 ")) {
                while (rsx.next()) {
                    nummer = Integer.parseInt(rsx.getObject("ID").toString());
                    art = (int) Double.parseDouble(rsx.getObject("art").toString());
                    alt = (int) Double.parseDouble(rsx.getObject("alt").toString());
                    hg = rsx.getDouble("hg");
                    h100 = Double.parseDouble(rsx.getObject("absHAlter100").toString());
                    dg = Double.parseDouble(rsx.getObject("dg").toString());
                    dmax = rsx.getDouble("d100");
                    g = Double.parseDouble(rsx.getObject("gha").toString());
                    if (hg > 5.0 && dg > 7.0 && g > 0.0) {
                        EtafelSim etsim = new EtafelSim();
                        id = nummer.toString();
                        st = etsim.newYTStand(st, id, 0.5);

                        GenDistribution gdb = new GenDistribution();
                        gdb.weibull(st, art, alt, dg, hg, dmax, g * st.size, false);
                        // missing data fuer die Verteilung generieren
                        for (int j = 0; j < st.ntrees; j++) {
                            if (st.tr[j].si <= -9) {
                                st.tr[j].si = h100;
                            }
                        }
                        SIofDistrib siod = new SIofDistrib();
                        FunctionInterpreter fi = new FunctionInterpreter();
                        siod.si(st, art, alt, dg, hg);
                        for (int j = 0; j < st.ntrees; j++) {
                            if (st.tr[j].h == 0.0) {
                                Tree tree = new Tree();
                                tree.code = art;
                                tree.sp = st.tr[j].sp;
                                tree.sp.dg = dg;
                                tree.sp.hg = hg;
                                tree.sp.h100 = 0.0;
                                tree.sp.d100 = 0.0;
                                tree.d = st.tr[j].d;
                                tree.code = st.tr[j].code;
                                tree.sp = st.tr[j].sp;
                                tree.st = st;
                                //                                st.tr[j].h = fi.getValueForTree(tree, tree.sp.spDef.uniformHeightCurveXML) + fi.getValueForTree(tree, tree.sp.spDef.heightVariationXML) * nd.value(3.0);
                                st.tr[j].h = fi.getValueForTree(tree, tree.sp.spDef.uniformHeightCurveXML);
                            }
                        }
                        for (int j = 0; j < st.ntrees; j++) {
                            st.tr[j].setMissingData();
                        }
                        GenerateXY gxy = null;
                        gxy = new GenerateXY();
                        gxy.setGroupRadius(0.0);
                        gxy.zufall(st);
                        st.sortbyd();
                        st.descspecies();
                    }
                    st.random.setRandomType(RandomNumber.PSEUDO);
                    st.descspecies();
                    if (st.ntrees > 0) {
                        LoadTreegrossStand lts = new LoadTreegrossStand();
                        lts.saveStand(con, st, id, alt, 0, 0);
                        lts.saveSpecies(con, st, id, alt, 0, 0);
                        //
                        st.grow(5, false);
                        st.sortbyd();
                        st.missingData();
                        st.descspecies();
                        lts.saveStand(con, st, id, alt, 1, 0);
                        lts.saveSpecies(con, st, id, alt, 1, 0);
                    }

                }
            }
        } catch (Exception e) {
            Logger.getLogger(DBAccessDialog.class.getName()).log(Level.SEVERE, "Problem with database", e);
        }
        dispose();
    }//GEN-LAST:event_feDataButtonActionPerformed

    private void simulationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulationButtonActionPerformed
        // Yield table simulation
        String aktivesDatenfile = "C:\\Dokumente und Einstellungen\\nagel\\Eigene Dateien\\jnProgramme\\ForestSimulator\\data_standsimulation\\localdata.mdb";
        ConnectionFactory dbconnAC = new ConnectionFactory();     // a class to manage the conection to a database
        try (Connection con = dbconnAC.openDBConnection(aktivesDatenfile, "", "")) {
            EtafelSim etsim = new EtafelSim();
            for (int iw = 1; iw < 3; iw++) {
                for (int i = 0; i < 5; i++) {
                    Integer ekl = 37 - (i * 4);
                    Integer ixno = iw;
                    String id = ixno.toString();
                    for (int j = 0; j < 1; j++) {
                        int age = 20;
                        st = etsim.newYTStand(st, id, 0.5);
                        st.ingrowthActive = false;
                        st.riskActive = false;
                        st.distanceDependent = true;
                        //st.randomGrowthEffects=true;
                        st.random.setRandomType(RandomNumber.PSEUDO);
                        st = etsim.addLayerFromTable(con, st, 711, ekl, age, 1.0);
                        st.descspecies();
                        //             st.sp[0].spDef.moderateThinning="12.0;0;1.0;120.0;1.0;130;130;1.0;140";
                        st.sp[0].trule.minCropTreeHeight = 12.0;
                        st.sp[0].trule.targetDiameter = 85.0;
                        st.sp[0].trule.targetCrownPercent = 100.0;
                        st.sp[0].trule.numberCropTreesWanted = 120;
                        st.sp[0].spDef.targetDiameter = 100.0;
                        st.sp[0].spDef.cropTreeNumber = 110;
                        Treatment2 treatment2 = new Treatment2();
                        treatment2.setAutoPlanting(st, false, false, 0.1, "511");
                        treatment2.setSkidTrails(st, true, 20.0, 4.0);
                        treatment2.setNatureProtection(st, 0, 0, false, 0.1, 200);
                        treatment2.setHarvestRegime(st, 2, 0, 180, 0.0, "0.3;");
                        treatment2.setThinningRegime(st, 0, 1.0, 0, 120, false);
                        if (st.ntrees > 0) {
                            age = (int) st.tr[0].age;
                            LoadTreegrossStand lts = new LoadTreegrossStand();
                            lts.saveStand(con, st, id, age, 0, ekl);
                            lts.saveSpecies(con, st, id, age, 0, ekl);
                            st.sortbyd();
                            st.missingData();
                            st.descspecies();

                            //
                            for (int jj = 0; jj < 20; jj++) {
                                treatment2.executeManager2(st);
                                st.executeMortality();
                                st.descspecies();
                                age = (int) st.tr[0].age;

                                lts.saveStand(con, st, id, age, 1, ekl);
                                lts.saveSpecies(con, st, id, age, 1, ekl);
                                st.grow(5, false);
                                st.descspecies();
                                System.out.println(jj + "  " + age);

                            }
                        }
                    }
                }
            }
        } catch (SQLException e) {
            Logger.getLogger(DBAccessDialog.class.getName()).log(Level.SEVERE, "Problem with database", e);
        }
        dispose();
    }//GEN-LAST:event_simulationButtonActionPerformed

    private void updateViewCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateViewCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateViewCheckboxActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox beginCheckBox;
    private javax.swing.JLabel biDataLabel;
    private javax.swing.JButton biPlotInfoButton;
    private javax.swing.JButton biUpdateButton;
    private javax.swing.JButton calculateAllButton;
    private javax.swing.JButton calculateStandButton;
    private javax.swing.JTextField databaseFilenameTextField;
    private javax.swing.JPanel elsaltoPanel;
    private javax.swing.JButton feDataButton;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton loadCircleButton;
    private javax.swing.JButton loadSPISButton;
    private javax.swing.JButton loadStandButton;
    private javax.swing.JLabel plotNumberLabel;
    private javax.swing.JTextField plotNumberTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JButton simulationButton;
    private javax.swing.JButton specialMixtureButton;
    private javax.swing.JTextField standNameTextField;
    private javax.swing.JCheckBox updateViewCheckbox;
    private javax.swing.JLabel yearsLabel;
    private javax.swing.JTextField yearsTextField;
    // End of variables declaration//GEN-END:variables
    
}
