/* http://www.nw-fva.de
   Version 2013-01-13

   (c) 2002 Juergen Nagel, Northwest German Forest Research Station, 
       Grätzelstr.2, 37079 Göttingen, Germany
       E-Mail: Juergen.Nagel@nw-fva.de
 
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT  WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
 */

package nwfva.biomass;

import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import treegross.base.*;

/**
 * Biomassedialog für den ForestSimulator
 * @author J. Nagel
 */
public class BiomassDialog extends javax.swing.JDialog {
    private static final Logger log = Logger.getLogger( nwfva.assortment.NWFVA_Nutzung.class.getName() );
    String progDir = "";
    String workDir = "";
    Stand st = null;
    BiomassPanel nbp = null;
/**
 * 
 * @param parent
 * @param modal
 * @param stand TreeGrOSS Stand
 * @param programDir Programmverzeichnis
 * @param interactive Möglichkeit andere xml Files zu lesen
 * @param workingDir Ausgabeverzeichnis
 */
    public BiomassDialog(java.awt.Frame parent, boolean modal, Stand stand, String programDir, boolean interactive,
        String workingDir, FileHandler logHandler) {
        super(parent, modal);
        initComponents();
        if (logHandler == null){
          try{
           Handler handler = new FileHandler("log.txt",true );
           handler.setFormatter(new SimpleFormatter());
           log.addHandler(handler );
           log.info( "Biomass-Dialog gestartet" );
          }
          catch (Exception e){};
        }
        else log.addHandler(logHandler );
        log.info("Biomass- Dialog");
        st = stand;
        String Test = programDir;
        nbp = new BiomassPanel(st, programDir, interactive, workingDir);
//        System.out.println(programDir+"  WD:"+workingDir);
        add(nbp);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nutrient Balance Dialog");

        jButton1.setText("Entnahmemengen auf der Basis der Sortimente berechnen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(1005, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nbp.calculateNutrientBalance();
        nbp.reloadTableAssortment();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
